# Generated by Django 5.0 on 2024-01-02 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4)),
                ('ticket_title', models.CharField(max_length=100)),
                ('ticket_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_resloved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=15)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('Severity', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', max_length=5)),
                ('is_assigned_to_engineer', models.BooleanField(default=False)),
                ('resolution_steps', models.TextField()),
            ],
        ),
    ]
